version: 2.1

orbs:
  node: circleci/node@5.0.1

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
        pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install

  print:
    docker:
      - image: cimg/node:16.10
    steps:
      - run: |
          echo "Installing dependencies..."

  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test

workflows:
  simple_workflow:
    jobs:
      - build
      - print
      - test:
          requires:
            - build
